-- TOTO EDGE Ver0.2 database schema
-- Run this in Supabase SQL Editor.

create table if not exists public.toto_rounds (
  id bigint generated by default as identity primary key,
  round_no text not null unique,
  title text,
  sales_start timestamptz,
  sales_end timestamptz,
  status text default 'draft',
  source_url text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  name text not null unique,
  short_name text,
  league text,
  created_at timestamptz default now()
);

create table if not exists public.matches (
  id bigint generated by default as identity primary key,
  round_no text not null references public.toto_rounds(round_no) on delete cascade,
  match_no int not null,
  kickoff timestamptz,
  league text,
  venue text,
  home_team text not null,
  away_team text not null,
  weather text default '未取得',
  home_rank int,
  away_rank int,
  home_points int,
  away_points int,
  home_last5 text,
  away_last5 text,
  home_goals_for int,
  home_goals_against int,
  away_goals_for int,
  away_goals_against int,
  home_win_rate numeric,
  away_win_rate numeric,
  home_rest_days int default 5,
  away_rest_days int default 5,
  home_injury_level int default 0,
  away_injury_level int default 0,
  vote_home numeric,
  vote_draw numeric,
  vote_away numeric,
  result_home_score int,
  result_away_score int,
  result_outcome text check (result_outcome in ('home','draw','away') or result_outcome is null),
  source_url text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(round_no, match_no)
);

create table if not exists public.predictions (
  id bigint generated by default as identity primary key,
  match_id bigint references public.matches(id) on delete cascade,
  model_version text not null default 'rule-v0.1',
  home_prob numeric not null,
  draw_prob numeric not null,
  away_prob numeric not null,
  pick text not null check (pick in ('home','draw','away')),
  confidence text not null,
  edge numeric not null,
  reasons jsonb not null default '[]'::jsonb,
  created_at timestamptz default now(),
  unique(match_id, model_version)
);

alter table public.toto_rounds enable row level security;
alter table public.teams enable row level security;
alter table public.matches enable row level security;
alter table public.predictions enable row level security;

-- Read-only policies for the app. Inserts are done with service role from local scripts.
do $$ begin
  create policy "rounds readable" on public.toto_rounds for select using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "teams readable" on public.teams for select using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "matches readable" on public.matches for select using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "predictions readable" on public.predictions for select using (true);
exception when duplicate_object then null; end $$;
