import { MatchInput } from './types'

export const sampleMatches: MatchInput[] = [
  { id: 1, round: '第0001回 toto', kickoff: '土 14:00', homeTeam: '鹿島', awayTeam: '横浜FM', venue: 'カシマ', homeRank: 2, awayRank: 8, homeRecentPoints: 12, awayRecentPoints: 7, homeGoalDiff: 14, awayGoalDiff: 4, homeHomeStrength: 82, awayAwayStrength: 58, homeRestDays: 6, awayRestDays: 3, weatherRisk: 2, homeInjuryRisk: 2, awayInjuryRisk: 8, motivationHome: 9, motivationAway: 6, publicVote: { home: 42, draw: 26, away: 32 } },
  { id: 2, round: '第0001回 toto', kickoff: '土 14:00', homeTeam: '浦和', awayTeam: '神戸', venue: '埼玉', homeRank: 6, awayRank: 1, homeRecentPoints: 8, awayRecentPoints: 13, homeGoalDiff: 5, awayGoalDiff: 18, homeHomeStrength: 73, awayAwayStrength: 76, homeRestDays: 5, awayRestDays: 5, weatherRisk: 1, homeInjuryRisk: 5, awayInjuryRisk: 3, motivationHome: 7, motivationAway: 9, publicVote: { home: 35, draw: 27, away: 38 } },
  { id: 3, round: '第0001回 toto', kickoff: '土 15:00', homeTeam: '川崎F', awayTeam: '柏', venue: '等々力', homeRank: 10, awayRank: 5, homeRecentPoints: 5, awayRecentPoints: 10, homeGoalDiff: 0, awayGoalDiff: 9, homeHomeStrength: 65, awayAwayStrength: 70, homeRestDays: 4, awayRestDays: 6, weatherRisk: 5, homeInjuryRisk: 6, awayInjuryRisk: 2, motivationHome: 6, motivationAway: 8, publicVote: { home: 49, draw: 25, away: 26 } },
  { id: 4, round: '第0001回 toto', kickoff: '土 16:00', homeTeam: '札幌', awayTeam: '福岡', venue: '札幌ド', homeRank: 17, awayRank: 11, homeRecentPoints: 4, awayRecentPoints: 7, homeGoalDiff: -12, awayGoalDiff: -1, homeHomeStrength: 49, awayAwayStrength: 52, homeRestDays: 6, awayRestDays: 4, weatherRisk: 0, homeInjuryRisk: 4, awayInjuryRisk: 5, motivationHome: 10, motivationAway: 6, publicVote: { home: 31, draw: 30, away: 39 } },
  { id: 5, round: '第0001回 toto', kickoff: '日 14:00', homeTeam: '広島', awayTeam: 'FC東京', venue: 'Eピース', homeRank: 3, awayRank: 12, homeRecentPoints: 11, awayRecentPoints: 5, homeGoalDiff: 16, awayGoalDiff: -4, homeHomeStrength: 84, awayAwayStrength: 45, homeRestDays: 7, awayRestDays: 4, weatherRisk: 3, homeInjuryRisk: 2, awayInjuryRisk: 7, motivationHome: 9, motivationAway: 5, publicVote: { home: 54, draw: 24, away: 22 } },
  { id: 6, round: '第0001回 toto', kickoff: '日 15:00', homeTeam: 'G大阪', awayTeam: 'C大阪', venue: 'パナスタ', homeRank: 7, awayRank: 9, homeRecentPoints: 8, awayRecentPoints: 8, homeGoalDiff: 6, awayGoalDiff: 3, homeHomeStrength: 70, awayAwayStrength: 62, homeRestDays: 5, awayRestDays: 5, weatherRisk: 4, homeInjuryRisk: 4, awayInjuryRisk: 4, motivationHome: 8, motivationAway: 8, publicVote: { home: 37, draw: 33, away: 30 } }
]
